export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";

export const CHANGE_CHECKOUT_STAGE = "CHANGE_CHECKOUT_STAGE";

export const CHANGE_QTY = "CHANGE_QTY";
